version: '3.3'

services:
  client:
    build: ./client
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 60s

  server:
      build: ./server
      command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      container_name: server
      volumes:
        - .:/server
      ports:
        - "8000:8000"
      depends_on:
        - db
      deploy:
        restart_policy:
          condition: on-failure
          delay: 3s
          max_attempts: 3
          window: 60s

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - server/env/production.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 60s

volumes:
  postgres_data:
  server: