version: '3.3'

services:
  client:
    build: ./client
    ports:
      - "80:80"

  server:
      build: ./server
      command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      container_name: server
      volumes:
        - .:/server
      ports:
        - "8000:8000"
      depends_on:
        - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data: