export const TOP_COMPANIES = [
  {
    id: 1,
    name: 'Webflow',
    field: 'Manufacturing',
    location: 'Remote or London',
    employees: 3,
    openPositions: 2,
    image: '',
  },
  {
    id: 2,
    name: 'Webflow',
    field: 'Manufacturing',
    location: 'Remote or London',
    employees: 3,
    openPositions: 2,
    image: '',
  },
  {
    id: 3,
    name: 'Webflow',
    field: 'Manufacturing',
    location: 'Remote or London',
    employees: 3,
    openPositions: 2,
    image: '',
  },
  {
    id: 4,
    name: 'Webflow',
    field: 'Manufacturing',
    location: 'Remote or London',
    employees: 3,
    openPositions: 2,
    image: '',
  },
  {
    id: 5,
    name: 'Webflow',
    field: 'Manufacturing',
    location: 'Remote or London',
    employees: 3,
    openPositions: 2,
    image: '',
  },
  {
    id: 6,
    name: 'Webflow',
    field: 'Manufacturing',
    location: 'Remote or London',
    employees: 3,
    openPositions: 2,
    image: '',
  },
];
