export const VACANCIES = [
  {
    id: 1,
    title: 'Product Manager (Operations)',
    company: 'Breef',
    location: 'Remote or London',
    employees: 3,
    apply: 'direct',
    image: '',
  },
  {
    id: 2,
    title: 'Product Manager (Operations)',
    company: 'Breef',
    location: 'Remote or London',
    employees: 3,
    apply: 'direct',
    image: '',
  },
  {
    id: 3,
    title: 'Product Manager (Operations)',
    company: 'Breef',
    location: 'Remote or London',
    employees: 3,
    apply: 'direct',
    image: '',
  },
  {
    id: 4,
    title: 'Product Manager (Operations)',
    company: 'Breef',
    location: 'Remote or London',
    employees: 3,
    apply: 'direct',
    image: '',
  },
  {
    id: 5,
    title: 'Product Manager (Operations)',
    company: 'Breef',
    location: 'Remote or London',
    employees: 3,
    apply: 'direct',
    image: '',
  },
  {
    id: 6,
    title: 'Product Manager (Operations)',
    company: 'Breef',
    location: 'Remote or London',
    employees: 3,
    apply: 'direct',
    image: '',
  },
];
